volumes:
  db_volume:

networks:
  skillfusion_network:

services:

# Service de base de données PostgreSQL
  db:
    image: postgres:18
    container_name: skillfusion_db
    environment:
      POSTGRES_USER: usersf
      POSTGRES_PASSWORD: usersf
      POSTGRES_DB: usersf
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql
    networks:
      - skillfusion_network

# Service de l'API Node.js
  api:
    build:
      context: ./api
      target: production
    container_name: skillfusion_api
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - skillfusion_network
    command: sh -c "npm run db:deploy && npm run db:seed && npm start"

  client:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: https://skillfusion.loicleger.fr
    container_name: skillfusion_client
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
      - db
    env_file:
      - ./client/.env
    networks:
      - skillfusion_network
    command: sh -c "node build/index.js"