
@BASE_URL=http://localhost:3000

### tools
GET {{BASE_URL}}/api/tools
Content-Type: application/json

### tools avec id
GET {{BASE_URL}}/api/tools/1
Content-Type: application/json

### creer une tool
POST {{BASE_URL}}/api/tools
Content-Type: application/json

{
    "name": "Marteau",
    "description": "Marteau pour les travaux de charpente"
}

### modifier une tool
PATCH {{BASE_URL}}/api/tools/6
Content-Type: application/json

{
    "name": "Marteau de charpentier",
    "description": "Marteau pour les travaux de charpente avec une tête en acier trempé"
}

### supprimer une tool
DELETE {{BASE_URL}}/api/tools/6
Content-Type: application/json
