# Etape de base pour les deux environements
FROM node:24-alpine AS base
WORKDIR /app
COPY package*.json ./

# Consignes de developpement
FROM base AS development
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]

# Consignes de production
FROM base AS production
RUN npm ci --omit-dev
COPY . .

CMD ["npm", "run", "start"]